# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.7'

services:
  mysql:
    image: mysql:8.0.26
    restart: always
    # If you want to relocate the mysql data (volume) to your local directory, uncomment the lines below
    # volumes:
    #   - ~/volumes/entando-bundle-cli/jeff-ent-bundle/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=jeff-ent-bundle-password
      - MYSQL_USER=jeff-ent-bundle-user
      - MYSQL_PASSWORD=jeff-ent-bundle-password
      - MYSQL_DATABASE=jeff-ent-bundle
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
